runs:
  - F:\Uni\2020_Semester XIV\Learning_Archive\Networks\Activations\maze0122

jobs:
  - type: table
    headers: activations
    results:
      time: true
    output: "../config/plots/network_experiments/activations_maze0122.tex"
