algorithm:
  name: "acer"
  verbose: 10
  policy:
    name: SimpleMazeCnnPolicy
    scale: false
  tensorboard_log: true
  buffer_size: 50000
  replay_start: 5000
  ent_coef: 0.001
  n_steps: 256
  gamma: 0.99
  replay_ratio: 4
  q_coef: 0.5
  lr_schedule: "linear"
  learning_rate: 0.0008