algorithm:
  cliprange: 0.2
  ent_coef: 1.0e-07
  gamma: 0.98
  lam: 0.99
  learning_rate: 0.0005
  n_steps: 512
  name: ppo2
  nminibatches: 16
  noptepochs: 12
  policy:
    name: SimpleMazeCnnPolicy
    scale: false
  tensorboard_log: true
  verbose: 1