algorithm:
  cliprange: 0.05
  cliprange_vf: null
  ent_coef: 1.0e-05
  gamma: 0.98
  lam: 0.95
  learning_rate:
    type: "linear"
    initial_value: 0.0025
    final_value: 0.0001
  n_steps: 128
  name: ppo2
  nminibatches: 4
  noptepochs: 16
  policy:
    name: SimpleMazeCnnPolicy
  tensorboard_log: true
  verbose: 10