algorithm:
  name: "a2c"
  policy:
    name: "MlpPolicy"
  learning_rate: 0.0001
  gamma: 0.99

env:
  name: "NumberEnv-v0"
  normalize:
    norm_obs: true
    norm_reward: true
    precompute: true
    samples: 10000
  n_envs: 8

meta:
  n_timesteps: 100000
  log_dir: "./logs/NumberEnv"
