algorithm:
  name: "dqn"
  verbose: 1
  policy:
    name: CnnPolicy
  tensorboard_log: true
  gamma: 0.9
  learning_rate: 0.001
  buffer_size: 1000000
  train_freq: 16
  batch_size: 8
  target_network_update_freq: 32000
  prioritized_replay: True
  prioritized_replay_alpha: 0.26
  prioritized_replay_beta0: 0.265
  learning_starts: 20000
  exploration_fraction: 0.3
  exploration_final_eps: 0.07


env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  frame_stack:
    n_stack: 4
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Labtest_Dqn"
  save_interval: 200000