algorithm:
  name: "dqn"
  verbose: 1
  policy:
    name: CnnPolicy
  tensorboard_log: true

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  frame_stack:
    n_stack: 4
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Labtest_Dqn"
  save_interval: 200000

search:
  resume: "./logs/Labtest_Dqn/2020_02_27_153359"
  n_timesteps: 3000000
  eval_method: "normal"
  n_test_episodes: 32
  n_trials: 100
  sampler: "tpe"
  pruner:
    method: "halving"
    min_resource: 400000