algorithm:
  name: "acer"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  buffer_size: 50000
  replay_start: 5000
  ent_coef: 0.00001
  n_steps: 128
  gamma: 0.99
  q_coef: 0.65
  lr_schedule: "linear"
  learning_rate: 0.025

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  n_envs: 32
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 5000000
  log_dir: "./logs/Labtest_Acer"
  save_interval: 200000