algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  learning_rate: 0.001
  nminibatches: 8
  n_steps: 512
  gamma: 0.9999
  ent_coef: 0.0014
  cliprange: 0.1
  lam: 0.95
  noptepochs: 20

env:
  name: "Maze0318Continuous-v1"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  frame_stack:
    n_stack: 4
  n_envs: 32

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Maze_Random_Robots"
  save_interval: 200000