algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  learning_rate:
    type: "linear"
    initial_value: 2.5e-4
  nminibatches: 16
  n_steps: 512

env:
  name: "Maze0318Continuous-v0"
  wrappers: ["env.wrappers.WarpGrayscaleFrame", "stable_baselines.common.atari_wrappers.MaxAndSkipEnv"]
  n_envs: 16
  frame_stack:
    n_stack: 4
  normalize:
    norm_reward: true
    norm_obs: true

meta:
  seed: 42
  n_timesteps: 15000000
  log_dir: "./logs/Labtest"
  save_interval: 200000