algorithm:
  name: "acktr"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  ent_coef: 0.001

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  frame_stack:
    n_stack: 4
  n_particles: 256
  reward_kwargs:
    gathering_reward: 0.0

meta:
  seed: 82
  n_timesteps: 100000000
  log_dir: "./logs/Acktr_Search"
  save_interval: 200000

search:
  n_timesteps: 3000000
  eval_method: "normal"
  n_test_episodes: 32
  n_trials: 40
  sampler: "tpe"
  pruner:
    method: "halving"
    min_resource: 400000
  env:
    n_envs:
      method: "categorical"
      choices: [16, 32, 64]