algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  learning_rate:
    type: "linear"
    initial_value: 0.001
    final_value: 0.00001
  nminibatches: 8
  n_steps: 512
  gamma: 0.9999
  ent_coef: 0.0014
  cliprange: 0.1
  lam: 0.95
  noptepochs: 20

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  n_envs: 32
  frame_stack:
    n_stack: 2
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Maze_Experimental"
  save_interval: 200000