algorithm:
  name: "dqn"
  verbose: 0
  policy:
    name: CnnPolicy
  tensorboard_log: true

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Labtest_Dqn"
  save_interval: 200000