algorithm:
  name: "acer"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  buffer_size: 32000
  replay_start: 50000
  ent_coef: 0.00001
  n_steps: 512
  gamma: 0.9999
  replay_ratio: 0
  q_coef: 0.5
  lr_schedule: "linear"
  learning_rate: 0.001

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  n_envs: 32
  frame_stack:
    n_stack: 4
  n_particles: 256

meta:
  seed: 82
  n_timesteps: 5000000
  log_dir: "./logs/Labtest_Acer"
  save_interval: 200000