algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  learning_rate:
    name: LinearSchedule
    initial_value: 1.0e-3
  nminibatches: 16
  n_steps: 512

env:
  name: "Maze0318-v0"
  wrappers: ["stable_baselines.common.atari_wrappers.WarpFrame"]
  n_envs: 64
  frame_stack:
    n_stack: 4

meta:
  seed: 42
  n_timesteps: 15000000
  log_dir: "./logs/Labtest"
  save_interval: 200000