algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true
  cliprange: 0.1
  ent_coef: 0.0014
  gamma: 0.9999
  lam: 0.95
  learning_rate: 0.001
  n_steps: 512
  nminibatches: 8
  noptepochs: 20

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  n_envs: 32
  frame_stack:
    n_stack: 4
  n_particles: 256
  reward_kwargs:
    gathering_reward: 0.0
  curiosity: false

meta:
  seed: 82
  n_timesteps: 3000000
  log_dir: "./logs/Labtest"
  save_interval: 200000