algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: CnnPolicy
  tensorboard_log: true

env:
  name: "Maze0318Continuous-v0"
  wrappers:
    - env.wrappers.WarpGrayscaleFrame
    - stable_baselines.common.atari_wrappers.MaxAndSkipEnv:
        skip: 4
  frame_stack:
    n_stack: 4
  normalize:
    norm_reward: true
    norm_obs: true
  robot_count: 256

meta:
  seed: 82
  n_timesteps: 100000000
  log_dir: "./logs/Labtest_Search"
  save_interval: 200000

search:
  n_timesteps: 3000000
  eval_method: "normal"
  n_test_episodes: 20
  n_trials: 40
  sampler: "tpe"
  pruner:
    method: "halving"
    min_resource: 400000
  env:
    n_envs:
      method: "categorial"
      choices: [16, 32, 64]