algorithm:
  name: "ppo2"
  verbose: 10
  policy:
    name: MlpPolicy
  cliprange_vf: -1
  tensorboard_log: true
  learning_rate:
    type: linear
    initial_value: 2.5e-4
    final_value: 1.0e-5
    final_point: 0.2

env:
  name: "CartPole-v1"
  n_envs: 8
  frame_stack:
    n_stack: 4
  normalize:
    norm_reward: false
    norm_obs: true

meta:
  seed: 42
  n_timesteps: 24000
  log_dir: "./logs/Labtest_CartPole"
  save_interval: 4000