algorithm:
  name: "acktr"
  verbose: 10
  policy:
    name: MlpPolicy
  tensorboard_log: true
  n_cpu_tf_sess:

env:
  name: "CartPole-v1"
  n_envs: 8
  frame_stack:
    n_stack: 4
  normalize:
    precompute: true
    samples: 10000
    norm_reward: false
    norm_obs: true

meta:
  seed: 42
  n_timesteps: 14000
  log_dir: "./logs/Labtest_CartPole"
  save_interval: 4000

search:
  n_timesteps: 8000
  eval_method: "normal"
  n_trials: 4
  sampler: "tpe"
