runs:
  - F:\Uni\2020_Semester XIV\Learning_Archive\Obs_Experiments\Size\Maze0318

jobs:
  - type: table
    headers: observation_size
    results:
      time: true
    output: "../config/plots/obs_experiments/Maze0318_obs_size.tex"