runs:
  - F:\Uni\2020_Semester XIV\Learning_Archive\Reward_Experimente\Maze0122\continuous\2020_06_09_192806
  - F:\Uni\2020_Semester XIV\Learning_Archive\Baseline\maze0122\2020_07_02_215639

jobs:
  - type: figure
    alias:
      "2020_06_09_192806": "Default Settings"
      "2020_07_02_215639": "Optimized Baseline"
    output: "../config/plots/baseline"
    