search:
  n_trials: 40
  sampler: "tpe"
  pruner:
    method: "halving"
    min_resource: 4000
  algorithm:
    learning_rate:
      method: "loguniform"
      low: 1.0e-4
      high: 0.1
  env:
    n_envs:
      method: "categorical"
      choices: [4, 8]